#!/usr/bin/env python3
"""
AI Image Analyzer  (v3.1 — Ensemble + Sigmoid)
=========================================
A forensic tool for detecting AI-generated images using multiple complementary
techniques: metadata forensics, C2PA provenance verification, noise
pattern analysis, frequency-domain analysis, statistical tests, and
visual-artifact detection.

Version 3.0 introduces major algorithmic upgrades:
  • **Non-linear score scaling** — sigmoid curve pushes strong signals
    toward 0% / 100% for clearer verdicts
  • **Dynamic weighting** — when EXIF/C2PA metadata is absent, physical
    signal tests (Noise, Frequency, Visual) receive boosted weights
  • **Text & grid anomaly detection** — catches AI-generated notebook
    pages, diagrams, and synthetic ink strokes
  • **New thresholds:** < 20% Real, 20–55% Uncertain, > 55% AI

Version 3.1 adds deep learning and ELA to the ensemble:
  • **Deep Learning Detector** — pre-trained Swin Transformer
    (`umm-maybe/AI-image-detector` via HuggingFace) extracts deep features;
    confidence-gated to avoid false positives on abstract/synthetic images
  • **Error Level Analysis (ELA)** — JPEG recompression error patterns,
    block-level uniformity, and compression artefact distribution

Scoring: 0-100% AI probability per test → score expansion → dynamic-weighted
         average → sigmoid scaling → verdict
  < 20 %      →  Real Camera Photo
  20–55 %     →  Uncertain / Mixed Signals
  > 55 %      →  AI-Generated

Educational / media-literacy use only.

Usage
-----
    python ai_image_analyzer.py <image_or_directory> [options]

Options
-------
    --batch             Scan all images in a directory
    --recursive         Search subdirectories in batch mode
    --summary           In batch mode, print only the summary table
    --json              Output results as JSON
    --html FILE         Write an interactive HTML report
    --no-color          Disable emoji output (for plain-text terminals)
    --verbose / -v      Print detailed findings for every test
    --quiet / -q        Print only the final verdict
    --threshold N       AI-probability threshold for verdict (0.0-1.0, default 0.55)

Dependencies
------------
    pip install pillow numpy opencv-python-headless scipy
    (optional) pip install exifread pyc2pa  # for enhanced metadata parsing
"""

from __future__ import annotations

import argparse
import base64
import glob
import io
import json
import math
import os
import struct
import sys
import warnings
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import cv2
import numpy as np
from PIL import Image, ExifTags

# ── Optional deep-learning imports (Swin Transformer AI detector) ─────────
_TORCH_AVAILABLE = True
try:
    import torch
    from transformers import AutoModelForImageClassification, AutoImageProcessor
    _DL_MODEL = None
    _DL_PROCESSOR = None
    _MODEL_NAME = "umm-maybe/AI-image-detector"
except ImportError:
    _TORCH_AVAILABLE = False
    _DL_MODEL = None
    _DL_PROCESSOR = None
    _MODEL_NAME = "umm-maybe/AI-image-detector"

# ── Suppress noisy warnings ──────────────────────────────────────────────
warnings.filterwarnings("ignore", category=UserWarning)
np.seterr(all="ignore")

# ── Constants ────────────────────────────────────────────────────────────

AI_KEYWORDS = [
    "midjourney", "dall-e", "dalle", "stable diffusion", "diffusion",
    "ai generated", "ai-generated", "deepai", "runwayml", "leonardo",
    "adobe firefly", "bard", "imagefx", "gen-2", "gen2",
    "stablediffusion", "discodiffusion", "dreambooth", "vintedreams",
    "clipdrop", "craiyon", "deepdream", "waifu2x", "upscale",
    "upscaled", "denoise", "denoised",
]

# Enhanced AI / provenance keyword list for raw metadata scanning
C2PA_AI_KEYWORDS = [
    "dall-e", "dalle", "midjourney", "stable diffusion", "stable-diffusion",
    "stable diffusion", "adobe firefly", "googleimagen", "imagen", "gen-2",
    "craiyon", "deepai", "runwayml", "runway", "leonardo",
    "imagefx", "bard", "makeager", "make-ager",
    "stablediffusion", "novelai", "novel-ai",
    "comfyui", "invokeai", "autoc1111", "automatic1111",
    "contentcredentials", "c2pa", "content credentials",
    "generated by", "ai-generated", "ai generated",
    "synthetic", "diffusion model", "generative model",
    "this image was generated", "ai art", "ai artwork",
    "deep learning", "neural network", "gan",
]

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".gif", ".tiff", ".tif"}

# Weighting for each forensic test (base weights; must sum to 1.0)
# Dynamic weighting adjusts these at runtime when EXIF metadata is
# absent — physical signal tests (Noise, Frequency, Visual) get boosted.
# C2PA test added for direct provenance verification.
# Deep Learning (Swin Transformer) and ELA added for robust ensemble.
TEST_WEIGHTS = {
    "metadata":      0.10,
    "c2pa":          0.10,   # C2PA & enhanced EXIF verification
    "noise":         0.20,   # noise pattern analysis
    "frequency":     0.15,   # frequency domain analysis (2D FFT)
    "statistical":   0.10,   # statistical anomaly detection
    "visual":        0.15,   # visual artifact + text/grid anomaly
    "deep":          0.15,   # deep learning (Swin Transformer)
    "error":         0.05,   # error level analysis (ELA)
}
# Total = 0.10+0.10+0.20+0.15+0.10+0.15+0.15+0.05 = 1.00

# Dynamic weight multipliers applied when EXIF metadata is absent.
# Physical signal tests are boosted to compensate for missing provenance.
DYNAMIC_WEIGHTS_NO_EXIF = {
    "metadata":      0.30,   # reduced (no EXIF to verify)
    "c2pa":          0.30,   # reduced (but still scans raw bytes)
    "noise":         1.25,   # boosted
    "frequency":     1.25,   # boosted
    "statistical":   1.25,   # boosted
    "visual":        1.35,   # boosted (text/grid anomaly detector)
    "deep":          1.00,   # neutral — DL model doesn't depend on EXIF
    "error":         1.20,   # boosted — ELA is a strong physical signal
}

# Verdict thresholds (v3.0 — recalibrated, tighter than v2.0)
AI_THRESHOLD  = 55.0   # above this --> AI-Generated
UNCERTAIN_LOW = 20.0   # below this --> Real Camera Photo


# ════════════════════════════════════════════════════════════════════════════
#  Data Classes
# ════════════════════════════════════════════════════════════════════════════

@dataclass
class TestResult:
    """Result of a single forensic test.

    ``score`` is the AI probability in **percent** (0–100):
      0  = certainly a real photograph
      50 = uncertain / mixed signals
      100 = certainly AI-generated
    """
    name: str
    score: float                       # 0–100 AI probability
    confidence: float                  # 0.0–1.0
    explanation: str = ""
    details: dict[str, Any] = field(default_factory=dict)

    @property
    def real_confidence(self) -> float:
        """Confidence that the image is a real photograph (100 − AI%)."""
        return max(0.0, 100.0 - self.score)

    @property
    def verdict(self) -> str:
        if self.score > AI_THRESHOLD:
            return "AI-Generated"
        elif self.score < UNCERTAIN_LOW:
            return "Real Camera"
        return "Uncertain"


@dataclass
class AnalysisReport:
    """Full analysis report combining all test results."""
    image_path: str
    image_size: tuple[int, int]
    file_size: int
    timestamp: str
    tests: list[TestResult]
    overall_score: float = 0.0          # 0–100 AI probability
    overall_confidence: float = 0.0     # 0.0–1.0
    verdict: str = "Uncertain"
    summary: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "image_path": self.image_path,
            "image_size": self.image_size,
            "file_size": self.file_size,
            "timestamp": self.timestamp,
            "verdict": self.verdict,
            "ai_probability": round(self.overall_score, 2),
            "real_probability": round(max(0.0, 100.0 - self.overall_score), 2),
            "confidence": round(self.overall_confidence, 4),
            "summary": self.summary,
            "tests": [
                {
                    "name": t.name,
                    "ai_probability": round(t.score, 2),
                    "real_probability": round(max(0.0, 100.0 - t.score), 2),
                    "confidence": round(t.confidence, 4),
                    "verdict": t.verdict,
                    "explanation": t.explanation,
                    "details": _json_safe(t.details),
                }
                for t in self.tests
            ],
        }


# ════════════════════════════════════════════════════════════════════════════
#  Utility Helpers
# ════════════════════════════════════════════════════════════════════════════

def load_image(image_path: str) -> tuple[np.ndarray, Image.Image, dict]:
    """Load an image as NumPy (BGR) + PIL (RGB) and extract EXIF before convert."""
    raw_img = Image.open(image_path)

    exif_dict: dict[int, Any] = {}
    try:
        exif_dict = raw_img._getexif() or {}
    except Exception:
        pass

    exif_bytes = raw_img.info.get("exif", b"")
    pil_img = raw_img.convert("RGB")
    if exif_bytes:
        pil_img.info["exif"] = exif_bytes

    cv_img = cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)
    return cv_img, pil_img, exif_dict


def _json_safe(obj: Any) -> Any:
    """Recursively convert non-JSON-serialisable values to safe types."""
    if isinstance(obj, bytes):
        try:
            return obj.decode("utf-8")
        except Exception:
            return repr(obj)
    if isinstance(obj, dict):
        return {str(k): _json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple, set, frozenset)):
        return [_json_safe(v) for v in obj]
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    if isinstance(obj, np.ndarray):
        return _json_safe(obj.tolist())
    if hasattr(obj, "isoformat"):
        return obj.isoformat()
    return obj


def human_readable_size(size: int) -> str:
    for unit in ["B", "KB", "MB", "GB"]:
        if size < 1024:
            return f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"


def html_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ════════════════════════════════════════════════════════════════════════════
#  Test 1 — Metadata Forensics
# ════════════════════════════════════════════════════════════════════════════

def test_metadata(pil_img: Image.Image, exif_dict: dict[int, Any]) -> TestResult:
    """
    Examine EXIF / XMP / IPTC metadata for AI-generation signatures.

    Recalibrated v2: Missing EXIF is **informative** but **not definitive** —
    many real screenshots and social-media images lack camera data.  Full
    camera EXIF is a strong real-photo signal.
    """
    findings: list[str] = []
    details: dict[str, Any] = {}
    ai_prob = 50.0   # neutral default
    confidence = 0.25  # metadata is a weak signal

    exif_human: dict[str, Any] = {}
    for tag_id, value in exif_dict.items():
        tag_name = ExifTags.TAGS.get(tag_id, f"tag_{tag_id}")
        exif_human[tag_name] = value
    details["exif"] = _json_safe(exif_human)

    # --- Software field ---
    software = exif_human.get("Software", "")
    details["software"] = str(software) if software else None

    if software:
        software_lower = str(software).lower()
        for kw in AI_KEYWORDS:
            if kw in software_lower:
                findings.append(f"AI keyword '{kw}' found in Software field: '{software}'")
                ai_prob = 95.0
                confidence = 0.95
                break
    else:
        details["no_software"] = True

    # --- Camera make / model ---
    camera_make = exif_human.get("Make", "")
    camera_model = exif_human.get("Model", "")
    details["camera_make"] = str(camera_make) if camera_make else None
    details["camera_model"] = str(camera_model) if camera_model else None

    has_timestamp = bool(exif_human.get("DateTimeOriginal")) or bool(exif_human.get("DateTime"))
    details["datetime_original"] = str(exif_human.get("DateTimeOriginal", "")) if exif_human.get("DateTimeOriginal") else None
    details["datetime"] = str(exif_human.get("DateTime", "")) if exif_human.get("DateTime") else None

    if not camera_model and not camera_make:
        findings.append("No camera make/model in EXIF (common for AI, screenshots, downloaded images)")
        ai_prob = min(95.0, ai_prob + 10.0)
        confidence = max(confidence, 0.25)
    else:
        combined_cam = f"{camera_make} {camera_model}".lower()
        for kw in AI_KEYWORDS:
            if kw in combined_cam:
                findings.append(f"AI keyword '{kw}' found in camera info")
                ai_prob = 90.0
                confidence = 0.9
                break
        else:
            findings.append("Camera make/model present in EXIF (consistent with a real photograph)")
            ai_prob = max(8.0, ai_prob - 25.0)
            confidence = max(confidence, 0.7)

    if has_timestamp:
        findings.append("Capture timestamp present (consistent with a real photograph)")
        ai_prob = max(5.0, ai_prob - 12.0)
        confidence = max(confidence, 0.5)
    else:
        findings.append("No capture timestamp in EXIF")
        ai_prob = min(95.0, ai_prob + 5.0)
        confidence = max(confidence, 0.25)

    # --- Resolution divisibility ---
    width, height = pil_img.size
    details["resolution"] = f"{width}x{height}"
    is_div_64 = (width % 64 == 0) and (height % 64 == 0)
    details["divisible_by_64"] = is_div_64

    if is_div_64:
        findings.append("Resolution divisible by 64 (common in diffusion model outputs)")
        ai_prob = min(95.0, ai_prob + 3.0)
        confidence = max(confidence, 0.3)

    explanation = "; ".join(findings) if findings else (
        "No metadata anomalies detected; camera EXIF present."
        if camera_model or camera_make else
        "No obvious AI metadata signatures detected."
    )

    return TestResult(
        name="Metadata Forensics",
        score=ai_prob,
        confidence=confidence,
        explanation=explanation,
        details=details,
    )


# ════════════════════════════════════════════════════════════════════════════
#  Test 1b — C2PA & Enhanced EXIF Metadata Verification
# ════════════════════════════════════════════════════════════════════════════

def _parse_jpeg_segments(raw_data: bytes) -> dict[str, bytes]:
    """Parse JPEG file segments and return a dict of segment marker → data."""
    segments: dict[str, bytes] = {}
    if len(raw_data) < 4 or raw_data[0] != 0xFF or raw_data[1] != 0xD8:
        return segments

    offset = 2  # skip SOI
    while offset < len(raw_data) - 1:
        if raw_data[offset] != 0xFF:
            offset += 1
            continue

        marker = raw_data[offset + 1]
        # SOI (0xD8), EOI (0xD9), RSTn (0xD0-0xD7) have no length field
        if marker in (0xD8, 0xD9) or 0xD0 <= marker <= 0xD7:
            offset += 2
            continue

        if marker == 0xDA:  # SOS (Start of Scan) — image data follows
            break

        if offset + 4 > len(raw_data):
            break

        seg_len = struct.unpack(">H", raw_data[offset + 2:offset + 4])[0]
        if seg_len < 2 or offset + 2 + seg_len > len(raw_data):
            break

        seg_data = raw_data[offset + 4:offset + 2 + seg_len]

        marker_names = {
            0xE1: "APP1",   # EXIF / XMP
            0xE6: "APP6",
            0xED: "APP13",  # Photoshop IRB / Adobe
            0xEE: "APP14",  # Adobe
            0xFE: "COM",    # Comment
        }
        name = marker_names.get(marker, f"0x{marker:02X}")
        segments[name] = seg_data

        offset += 2 + seg_len

    return segments


def _parse_png_chunks(raw_data: bytes) -> dict[str, list[bytes]]:
    """Parse PNG file chunks and return a dict of chunk type → list of data."""
    chunks: dict[str, list[bytes]] = {}
    if len(raw_data) < 8 or raw_data[:8] != b"\x89PNG\r\n\x1a\n":
        return chunks

    offset = 8  # skip PNG signature
    while offset + 8 <= len(raw_data):
        try:
            length = struct.unpack(">I", raw_data[offset:offset + 4])[0]
        except struct.error:
            break
        if offset + 12 + length > len(raw_data):
            break

        chunk_type = raw_data[offset + 4:offset + 8].decode("ascii", errors="replace")
        chunk_data = raw_data[offset + 8:offset + 8 + length]

        chunks.setdefault(chunk_type, []).append(chunk_data)

        # CRC (4 bytes) — skip to next chunk
        offset += 12 + length

    return chunks


def _extract_xmp(raw_data: bytes) -> str:
    """Extract XMP metadata as a string from raw image bytes."""
    xmp_parts: list[str] = []

    # JPEG: look in APP1 segments for XMP namespace
    segments = _parse_jpeg_segments(raw_data)
    for seg_data in segments.values():
        if b"http://ns.adobe.com/xap/1.0/" in seg_data or b"<x:xmpmeta" in seg_data:
            try:
                # XMP data starts after the namespace URI
                ns_end = seg_data.find(b"http://ns.adobe.com/xap/1.0/")
                if ns_end >= 0:
                    xmp_start = ns_end + len(b"http://ns.adobe.com/xap/1.0/")
                    # Find the end of the XMP packet
                    xmp_end = seg_data.rfind(b"</x:xmpmeta>")
                    if xmp_end > xmp_start:
                        xmp_data = seg_data[xmp_start:xmp_end + len(b"</x:xmpmeta>")]
                        xmp_parts.append(xmp_data.decode("utf-8", errors="replace"))
            except Exception:
                pass

    # PNG: look in iTXt chunks for XMP
    chunks = _parse_png_chunks(raw_data)
    for chunk_data in chunks.get("iTXt", []):
        # iTXt format: keyword, compression_flag, compression_method,
        #                language_tag, translated_keyword, text
        try:
            keyword_end = chunk_data.find(b"\x00")
            if keyword_end == -1:
                continue
            keyword = chunk_data[:keyword_end].decode("utf-8", errors="replace")
            # Skip: compression_flag (1), compression_method (1), language_tag (null-terminated)
            remaining = chunk_data[keyword_end + 1:]
            if remaining and (keyword.lower().startswith("xml") or "xmp" in keyword.lower()):
                xmp_parts.append(remaining.decode("utf-8", errors="replace"))
        except Exception:
            pass

    # Also scan for raw XMP packets in the file
    for pattern in [b"<x:xmpmeta", b"<rdf:RDF"]:
        idx = raw_data.find(pattern)
        if idx >= 0:
            end_idx = raw_data.find(b">", idx)
            if end_idx > idx:
                # Try to extract a reasonable chunk of XMP
                xmp_text = raw_data[idx:end_idx + 5000].decode("utf-8", errors="replace")
                xmp_parts.append(xmp_text)

    return "\n".join(xmp_parts)


def _search_metadata_strings(raw_data: bytes, exif_dict: dict) -> list[str]:
    """Search raw file bytes and EXIF dict for AI-related strings."""
    found: list[str] = []
    raw_lower = raw_data.lower() if raw_data else b""

    for kw in C2PA_AI_KEYWORDS:
        kw_bytes = kw.encode("utf-8").lower()
        if kw_bytes in raw_lower:
            found.append(kw)
        # Also check EXIF dict values
        for val in exif_dict.values():
            if isinstance(val, bytes):
                if kw_bytes in val.lower():
                    if kw not in found:
                        found.append(kw)
            elif isinstance(val, str):
                if kw in val.lower():
                    if kw not in found:
                        found.append(kw)

    return found


def test_c2pa_exif(image_path: str, pil_img: Image.Image, exif_dict: dict[int, Any]) -> TestResult:
    """
    Enhanced C2PA and EXIF metadata verification.

    Uses raw byte parsing (fallback when exifread / pyc2pa are unavailable)
    to detect:

    • **C2PA ContentCredentials** manifests (embedded provenance)
    • **AI tool signatures** in EXIF, XMP, IPTC, and raw header data:
      DALL-E, Midjourney, Adobe Firefly, Stable Diffusion, etc.
    • **Adobe Photoshop IRB** data (APP13 segments)
    • **Missing provenance** — no camera EXIF, no timestamps, no provenance

    This test is definitive when it finds a direct AI signature (high
    confidence), and neutral when no signatures are found.
    """
    findings: list[str] = []
    details: dict[str, Any] = {}
    ai_prob = 50.0
    confidence = 0.3

    details["image_format"] = pil_img.format or "unknown"

    # Read raw bytes for deep metadata extraction
    raw_data: bytes = b""
    try:
        with open(image_path, "rb") as f:
            raw_data = f.read()
    except Exception:
        pass

    # --- C2PA ContentCredentials detection ---
    c2pa_markers = []
    c2pa_indicators = [
        b"contentcredentials", b"c2pa", b"content_credentials",
        b"contentauthenticity", b"cai_verify",
        b"http://c2pa.org", b"https://c2pa.org",
        b"adobe.contentauthenticity", b"manifest",
        b"stds:hash", b"adobe:signature",
    ]

    raw_lower = raw_data.lower() if raw_data else b""
    for indicator in c2pa_indicators:
        if indicator in raw_lower:
            c2pa_markers.append(indicator.decode("utf-8", errors="replace"))

    details["c2pa_markers"] = c2pa_markers

    if c2pa_markers:
        findings.append(f"C2PA / ContentCredentials metadata found: {', '.join(c2pa_markers)}")
        # C2PA presence alone is not an AI signal — it means provenance was
        # attached. But if combined with AI keywords, it's a strong signal.
        confidence = max(confidence, 0.4)

    # --- XMP extraction and analysis ---
    xmp_text = ""
    if raw_data:
        xmp_text = _extract_xmp(raw_data)

    details["xmp_found"] = bool(xmp_text)
    if xmp_text:
        xmp_lower = xmp_text.lower()
        details["xmp_length"] = len(xmp_text)

        # Check XMP for AI keywords
        xmp_ai_found = []
        for kw in C2PA_AI_KEYWORDS:
            if kw in xmp_lower:
                xmp_ai_found.append(kw)
        details["xmp_ai_keywords"] = xmp_ai_found

        if xmp_ai_found:
            findings.append(f"AI tool signatures found in XMP metadata: {', '.join(xmp_ai_found[:5])}")
            ai_prob = min(95.0, ai_prob + 30.0)
            confidence = max(confidence, 0.8)

        # Check XMP CreatorTool
        for marker in ["creatortool", "creator tool", "software", "author",
                        "artist", "credit", "source", "jobname"]:
            idx = xmp_lower.find(marker)
            if idx >= 0:
                # Extract surrounding text
                start = max(0, idx - 50)
                end = min(len(xmp_text), idx + 200)
                context = xmp_text[start:end].strip()
                context_lower = context.lower()
                for kw in C2PA_AI_KEYWORDS:
                    if kw in context_lower:
                        findings.append(f"AI-related text found in XMP field '{marker}': ...{context[:80]}...")
                        ai_prob = min(95.0, ai_prob + 20.0)
                        confidence = max(confidence, 0.7)
                        break
    else:
        details["xmp_found"] = False

    # --- Search raw bytes for AI keywords ---
    ai_keywords_found = []
    if raw_data:
        ai_keywords_found = _search_metadata_strings(raw_data, exif_dict)

    details["raw_ai_keywords"] = ai_keywords_found

    if ai_keywords_found:
        findings.append(
            f"AI-related strings found in raw metadata: {', '.join(ai_keywords_found[:5])}"
        )
        ai_prob = min(95.0, ai_prob + 25.0)
        confidence = max(confidence, 0.75)

    # --- Adobe Photoshop IRB / APP13 check ---
    adobe_segments = {k: v for k, v in _parse_jpeg_segments(raw_data).items() if k == "APP13"}
    if adobe_segments:
        details["photoshop_app13_found"] = True
        findings.append("Adobe Photoshop APP13 (IRB) segment detected — may contain provenance data")
        confidence = max(confidence, 0.5)
    else:
        details["photoshop_app13_found"] = False

    # --- EXIF completeness ---
    if exif_dict:
        exif_keys = list(exif_dict.keys())
        details["exif_tag_count"] = len(exif_keys)
        details["exif_tags"] = _json_safe({ExifTags.TAGS.get(k, f"tag_{k}"): str(v)[:100]
                                            for k, v in exif_dict.items()})

        # Check for comprehensive camera EXIF
        has_camera = bool(exif_dict.get(271)) or bool(exif_dict.get(272))  # Make, Model
        has_iso = bool(exif_dict.get(34855))    # ISOSpeedRatings
        has_focal = bool(exif_dict.get(37386))  # FocalLength
        has_exposure = bool(exif_dict.get(33437)) or bool(exif_dict.get(33434))  # FNumber, ExposureTime

        exif_completeness = sum([has_camera, has_iso, has_focal, has_exposure])
        details["exif_completeness"] = f"{exif_completeness}/4"

        if exif_completeness >= 3:
            findings.append(
                f"Rich camera EXIF present ({exif_completeness}/4 key fields: "
                f"make/model, ISO, focal length, exposure) — strong real-photo signal"
            )
            ai_prob = max(10.0, ai_prob - 30.0)
            confidence = max(confidence, 0.8)
        elif exif_completeness >= 1:
            findings.append(f"Partial EXIF present ({exif_completeness}/4 fields).")
            ai_prob = max(25.0, ai_prob - 10.0)
            confidence = max(confidence, 0.4)
    else:
        details["exif_tag_count"] = 0
        findings.append("No EXIF data found — no camera metadata present")
        # Metadata Forensics test already handles missing-EXIF as AI signal;
        # C2PA test stays neutral and focuses on provenance signatures.

    # --- Final verdict for this test ---
    explanation = "; ".join(findings) if findings else (
        "No C2PA or AI metadata signatures detected; EXIF provenance present.")

    return TestResult(
        name="C2PA Metadata Verification",
        score=ai_prob,
        confidence=confidence,
        explanation=explanation,
        details=details,
    )


# ════════════════════════════════════════════════════════════════════════════
#  Test 2 — Noise Pattern Analysis
# ════════════════════════════════════════════════════════════════════════════

def test_noise(cv_img: np.ndarray) -> TestResult:
    """
    Analyse noise patterns.

    Recalibrated v2:
      • Natural ISO noise **varies** spatially → strong REAL signal
      • Bayer CFA interpolation patterns → strong REAL signal
      • Uniform noise → AI signal (but weighted less)
    """
    findings: list[str] = []
    details: dict[str, Any] = {}
    ai_prob = 50.0
    confidence = 0.5

    gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape

    # Guard against very small images
    if h < 64 or w < 64:
        return TestResult(
            name="Noise Pattern Analysis",
            score=50.0,
            confidence=0.2,
            explanation="Image too small for reliable noise analysis.",
            details={"noise_skip": "Image smaller than 64x64"},
        )

    # --- Regional noise variance ---
    block_size = 64
    noise_levels: list[float] = []

    for i in range(0, h - block_size + 1, block_size):
        for j in range(0, w - block_size + 1, block_size):
            block = gray[i:i + block_size, j:j + block_size].astype(np.float64)
            lap = cv2.Laplacian(block.astype(np.uint8), cv2.CV_64F)
            mad = np.median(np.abs(lap - np.median(lap)))
            sigma_est = mad * 1.4826
            noise_levels.append(sigma_est)

    noise_array = np.array(noise_levels)
    noise_cv = float(np.std(noise_array) / (np.mean(noise_array) + 1e-12))

    details["noise_regional_cv"] = round(noise_cv, 4)
    details["noise_regional_std"] = round(float(np.std(noise_array)), 4)
    details["noise_regional_mean"] = round(float(np.mean(noise_array)), 4)

    if noise_cv > 0.20:
        findings.append(
            f"Noise varies naturally across regions (CV={noise_cv:.3f}). "
            f"Consistent with real camera sensor noise."
        )
        ai_prob = max(10.0, ai_prob - 28.0)
        confidence = max(confidence, 0.7)
    elif noise_cv > 0.08:
        findings.append(f"Noise variation is moderate (CV={noise_cv:.3f}).")
        ai_prob = min(95.0, ai_prob + 5.0)
        confidence = max(confidence, 0.4)
    else:
        findings.append(
            f"Noise is unusually uniform (CV={noise_cv:.3f}). "
            f"Real photos typically show spatial noise variation."
        )
        ai_prob = min(95.0, ai_prob + 22.0)
        confidence = max(confidence, 0.7)

    # --- Chroma noise ---
    b, g, r = cv2.split(cv_img)
    chroma_noise_b = float(np.std(b.astype(np.float64) - g.astype(np.float64)))
    chroma_noise_r = float(np.std(r.astype(np.float64) - g.astype(np.float64)))
    avg_chroma_noise = (chroma_noise_b + chroma_noise_r) / 2.0
    details["chroma_noise"] = round(avg_chroma_noise, 4)

    if avg_chroma_noise > 3.0:
        findings.append(f"Chroma noise present ({avg_chroma_noise:.2f}).")
        # Only count as real signal if CFA patterns are also detected
        cfa_pre = _check_cfa_artifacts(gray, b, g, r)
        if cfa_pre > 0.10:
            findings.append("Combined with CFA detection — consistent with real sensor chroma noise.")
            ai_prob = max(15.0, ai_prob - 12.0)
            confidence = max(confidence, 0.6)
        else:
            findings.append("But no CFA patterns — chroma noise may be from synthesis, not sensor.")
            confidence = max(confidence, 0.3)
    elif avg_chroma_noise < 1.0:
        findings.append(f"Very low chroma noise ({avg_chroma_noise:.2f}) — AI images can lack sensor chroma noise.")
        ai_prob = min(80.0, ai_prob + 12.0)
        confidence = max(confidence, 0.5)

    # --- CFA (Bayer) pattern detection ---
    cfa_score = _check_cfa_artifacts(gray, b, g, r)
    details["cfa_detection_score"] = round(cfa_score, 4)

    if cfa_score > 0.10:
        findings.append(
            f"CFA/Bayer interpolation patterns detected (score={cfa_score:.3f}). "
            f"Strong indicator of a real digital camera sensor."
        )
        ai_prob = max(5.0, ai_prob - 25.0)
        confidence = max(confidence, 0.8)
    else:
        findings.append("No CFA interpolation patterns detected — consistent with direct RGB synthesis.")
        ai_prob = min(95.0, ai_prob + 8.0)
        confidence = max(confidence, 0.5)

    explanation = "; ".join(findings)
    return TestResult(
        name="Noise Pattern Analysis",
        score=ai_prob,
        confidence=confidence,
        explanation=explanation,
        details=details,
    )


def _check_cfa_artifacts(gray: np.ndarray, b: np.ndarray, g: np.ndarray, r: np.ndarray) -> float:
    """Check for Colour Filter Array (CFA) interpolation artifacts.

    Only samples from **non-uniform** regions to avoid false positives on
    images with large flat areas (e.g. notebook pages, white backgrounds).

    Additionally applies a background-smoothness gate: if the background
    is hyper-smooth (std < 5) but the cross-channel HF correlation is
    very high (> 0.50), the correlation is likely from synthetic content
    rather than genuine Bayer interpolation — the score is dampened.
    """
    try:
        h, w = gray.shape
        if h < 40 or w < 40:
            return 0.0

        # ── Background smoothness check (for false-positive suppression) ──
        lap = cv2.Laplacian(gray, cv2.CV_64F)
        active_mask = np.abs(lap) > 1.0  # pixels with real detail
        smooth_fraction = float((h * w - active_mask.sum()) / (h * w))
        if active_mask.sum() < 100:
            return 0.0  # too uniform — can't assess CFA

        b_hf = b.astype(np.float64) - cv2.GaussianBlur(b.astype(np.float64), (0, 0), 1)
        g_hf = g.astype(np.float64) - cv2.GaussianBlur(g.astype(np.float64), (0, 0), 1)
        r_hf = r.astype(np.float64) - cv2.GaussianBlur(r.astype(np.float64), (0, 0), 1)

        # Flatten and filter to active pixels only
        b_flat = b_hf[active_mask]
        g_flat = g_hf[active_mask]
        r_flat = r_hf[active_mask]

        bg_corr = np.corrcoef(b_flat, g_flat)[0, 1]
        gr_corr = np.corrcoef(g_flat, r_flat)[0, 1]
        br_corr = np.corrcoef(b_flat, r_flat)[0, 1]

        if any(np.isnan(c) for c in [bg_corr, gr_corr, br_corr]):
            return 0.0

        avg_correlation = (abs(bg_corr) + abs(gr_corr) + abs(br_corr)) / 3.0

        # ── False-positive suppression ────────────────────────────────
        # Extremely high cross-channel HF correlation (> 0.50) combined
        # with a large smooth background is characteristic of AI generation,
        # not genuine Bayer CFA interpolation.  Real camera photos have
        # textured backgrounds (paper grain, sensor noise) that keep the
        # smooth pixel fraction low (< 10%) even when CFA is present.
        if avg_correlation > 0.50 and smooth_fraction > 0.10:
            return 0.0  # Suppress — likely synthetic correlation

        return float(avg_correlation)
    except Exception:
        return 0.0


# ════════════════════════════════════════════════════════════════════════════
#  Text & Grid Anomaly Detector (helper)
# ════════════════════════════════════════════════════════════════════════════

def _detect_text_grid_anomalies(cv_img: np.ndarray) -> tuple[float, dict[str, Any]]:
    """
    Detect AI-generated text / diagram anomalies.

    Works with **any** background colour (white, coloured, or gradient).
    AI-generated notebook pages, diagrams, and text images lack the
    subtle imperfections of real photographs:
    - Hyper-smooth backgrounds (no paper texture, no sensor noise)
    - Synthetic ink strokes (uniform colour, no natural pen variation)
    - Perfectly periodic grid / text-line patterns
    - Overly regular edge spacing / dense edge rows

    Returns ``(anomaly_score, details)`` where *anomaly_score* is 0-50
    (added to the Visual test's AI probability).
    """
    gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape
    if h < 64 or w < 64:
        return 0.0, {"anomaly_skip": "Image too small"}

    b, g, r = cv2.split(cv_img)
    details: dict[str, Any] = {}
    score = 0.0

    # -- 1. Local variance (smoothness) -- catches gradient backgrounds --
    # Laplacian misses gradient backgrounds (low Laplacian but high std).
    # Local variance within a 9x9 window correctly identifies uniform areas.
    local_mean = cv2.boxFilter(gray.astype(np.float64), -1, (9, 9))
    local_sqmean = cv2.boxFilter(gray.astype(np.float64) ** 2, -1, (9, 9))
    local_var = np.maximum(0, local_sqmean - local_mean ** 2)
    local_std = np.sqrt(local_var)

    uniform_mask = (local_var < 16.0).astype(np.uint8)  # std < 4
    uniform_fraction = float(uniform_mask.sum()) / (h * w)
    details["uniform_pixel_coverage"] = round(uniform_fraction, 4)

    if uniform_fraction > 0.70:
        details["large_uniform_background"] = True
        score += 25.0
    elif uniform_fraction > 0.40:
        details["moderate_uniform_background"] = True
        score += 15.0
    elif uniform_fraction > 0.15:
        score += 5.0

    # -- 2. Background texture smoothness (no paper grain / sensor noise) --
    if uniform_mask.sum() > 200:
        avg_local_std = float(np.mean(local_std[uniform_mask > 0]))
        details["avg_local_std"] = round(avg_local_std, 4)

        if avg_local_std < 1.5:
            details["hyper_smooth_background"] = True
            score += 25.0
        elif avg_local_std < 3.0:
            details["smooth_background"] = True
            score += 10.0

    # -- 3. Periodic grid / text-line patterns via FFT --
    gray_f = gray.astype(np.float64) - np.mean(gray)
    fft = np.fft.fft2(gray_f)
    magnitude = np.log1p(np.abs(np.fft.fftshift(fft)))
    center_h, center_w = h // 2, w // 2

    h_profile = magnitude[center_h, :].copy()
    v_profile = magnitude[:, center_w].copy()

    hw = min(w // 12, 40)
    h_profile[max(0, center_w - hw):center_w + hw] = 0
    hh = min(h // 12, 40)
    v_profile[max(0, center_h - hh):center_h + hh] = 0

    h_threshold = np.mean(h_profile) + 2.0 * np.std(h_profile)
    v_threshold = np.mean(v_profile) + 2.0 * np.std(v_profile)
    h_peaks = int(np.sum(h_profile > h_threshold))
    v_peaks = int(np.sum(v_profile > v_threshold))
    details["horizontal_freq_peaks"] = h_peaks
    details["vertical_freq_peaks"] = v_peaks

    if h_peaks >= 3 or v_peaks >= 3:
        details["periodic_grid_pattern"] = True
        score += 20.0
    elif h_peaks >= 1 or v_peaks >= 1:
        score += 5.0

    # -- 4. Edge-row density & regularity (text / diagram patterns) --
    edges = cv2.Canny(gray, 50, 150)

    edge_rows = np.sum(edges > 0, axis=1)
    edge_row_indices = np.where(edge_rows > 0)[0]
    if len(edge_row_indices) > 5:
        gaps = np.diff(edge_row_indices).astype(float)
        gap_mean = float(np.mean(gaps))
        gap_std = float(np.std(gaps))
        edge_row_density = len(edge_row_indices) / h
        details["edge_row_density"] = round(edge_row_density, 4)

        if edge_row_density > 0.95 and gap_mean < 3 and uniform_fraction > 0.15:
            details["dense_edge_rows"] = True
            details["gap_mean"] = round(gap_mean, 4)
            score += 20.0
        elif gap_mean > 5:
            regularity = 1.0 - min(1.0, gap_std / (gap_mean + 1e-8))
            details["edge_row_regularity"] = round(regularity, 4)
            if regularity > 0.85:
                details["regular_edge_spacing"] = True
                score += 15.0

    # -- 5. Color uniformity of ink regions (synthetic strokes) --
    dark_pixels = gray < 100
    if dark_pixels.sum() > 500:
        dark_b = b[dark_pixels]
        dark_g = g[dark_pixels]
        dark_r = r[dark_pixels]
        ink_color_std = float(np.mean([
            np.std(dark_b.astype(np.float64)),
            np.std(dark_g.astype(np.float64)),
            np.std(dark_r.astype(np.float64)),
        ]))
        details["ink_color_std"] = round(ink_color_std, 4)

        if ink_color_std < 15.0 and uniform_fraction > 0.15:
            details["uniform_ink_color"] = True
            score += 10.0

    details["total_anomaly_score"] = round(score, 2)
    return min(50.0, score), details



# ════════════════════════════════════════════════════════════════════════════
#  Test 2.5 — Deep Learning Detector (Swin Transformer)
# ════════════════════════════════════════════════════════════════════════════

_DL_MODEL_CACHE: dict[str, Any] = {}


def _load_dl_model() -> Any:
    """Lazily download and load the Swin Transformer AI detector model.

    Uses ``umm-maybe/AI-image-detector`` from HuggingFace Hub — a
    fine-tuned Swin Transformer that classifies images as
    *artificial* (AI-generated) or *human* (real photograph).

    The model is cached in-memory after the first load.
    """
    if not _TORCH_AVAILABLE:
        return None

    cache_key = _MODEL_NAME
    if cache_key in _DL_MODEL_CACHE:
        return _DL_MODEL_CACHE[cache_key]

    try:
        import torch
        from transformers import AutoModelForImageClassification, AutoImageProcessor

        processor = AutoImageProcessor.from_pretrained(_MODEL_NAME)
        model = AutoModelForImageClassification.from_pretrained(_MODEL_NAME)
        model.eval()
        if torch.cuda.is_available():
            model = model.to("cuda")

        _DL_MODEL_CACHE[cache_key] = (model, processor)
        return _DL_MODEL_CACHE[cache_key]
    except Exception as exc:
        warnings.warn(f"Deep learning model load failed: {exc}")
        _DL_MODEL_CACHE[cache_key] = None
        return None


def test_deep_learning(cv_img: np.ndarray) -> TestResult:
    """Run the pre-trained Swin Transformer AI detector on the image.

    Uses ``umm-maybe/AI-image-detector`` which classifies images as
    'artificial' (AI-generated) or 'human' (real photograph).

    The model's 'artificial' probability is mapped to an AI
    probability score.
    """
    result = _load_dl_model()
    if result is None:
        return TestResult(
            name="Deep Learning Detector (Swin Transformer)",
            score=50.0,
            confidence=0.0,
            explanation="Swin Transformer model unavailable (transformers/torch not installed).",
            details={"model": _MODEL_NAME, "error": "model_not_available"},
        )

    model, processor = result

    try:
        import torch

        # Convert OpenCV BGR to RGB PIL image
        rgb = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        pil_img = Image.fromarray(rgb)

        # Handle small images by resizing up
        min_size = 32
        if pil_img.size[0] < min_size or pil_img.size[1] < min_size:
            pil_img = pil_img.resize((224, 224), Image.LANCZOS)

        # Preprocess
        inputs = processor(images=pil_img, return_tensors="pt")
        if torch.cuda.is_available():
            inputs = {k: v.to("cuda") for k, v in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)
            logits = outputs.logits

        # Get probabilities via softmax
        probs = torch.softmax(logits, dim=-1)
        probs = probs.cpu().numpy()[0]

        # --- Dynamically resolve the AI/Fake vs Real class indices from the
        # model's config (config.id2label) instead of hardcoding positions ---
        # Hardcoding "index 0 = artificial, index 1 = human" is fragile: if a
        # future model revision (or a drop-in replacement) swaps the label
        # order, every score would silently invert.  We therefore identify
        # the AI and the Real class by *name* and only fall back to the
        # positional convention for umm-maybe/AI-image-detector
        # ({"0": "artificial", "1": "human"}) when labels are generic.
        label_map = getattr(model.config, "id2label", None) or {}
        label_names = {str(k): str(v).lower() for k, v in label_map.items()}

        _AI_LABEL_KEYWORDS = (
            "artificial", "ai", "fake", "synthetic", "generated",
            "manmade", "gan", "deepfake", "diffusion",
        )
        _REAL_LABEL_KEYWORDS = (
            "human", "real", "photo", "photograph", "authentic",
            "natural", "genuine", "camera",
        )

        num_classes = int(logits.shape[-1])
        ai_index = None
        real_index = None
        for i in range(num_classes):
            name = label_names.get(str(i), "")
            if ai_index is None and any(kw in name for kw in _AI_LABEL_KEYWORDS):
                ai_index = i
            if real_index is None and any(kw in name for kw in _REAL_LABEL_KEYWORDS):
                real_index = i

        # Positional fallbacks (preserve historical behaviour for the
        # umm-maybe/AI-image-detector model which ships {"0": "artificial",
        # "1": "human"}).
        if ai_index is None:
            ai_index = 0
        if real_index is None or real_index == ai_index:
            real_index = 1 if num_classes > 1 else ai_index

        artificial_prob = float(probs[ai_index]) if 0 <= ai_index < len(probs) else 0.0
        human_prob = (
            float(probs[real_index])
            if 0 <= real_index < len(probs) and real_index != ai_index
            else 0.0
        )
        ai_score = artificial_prob * 100.0

        # The Swin model is trained on natural photographs and tends to
        # misclassify abstract/synthetic patterns (diagrams, fractals,
        # notebook renders) as 'human'.  We gate the reported confidence
        # so that low-certainty predictions carry proportionally less
        # weight in the ensemble:
        #   > 0.95 certainty → full confidence (reliable)
        #   0.85–0.95 → halved (use with caution)
        #   < 0.85 → heavily discounted (likely out-of-distribution)
        certainty = max(artificial_prob, human_prob)
        if certainty > 0.95:
            confidence = certainty
        elif certainty > 0.85:
            confidence = certainty * 0.5
        else:
            confidence = certainty * 0.2

        # Build explanation
        top_class = ai_index if artificial_prob > human_prob else real_index
        top_label = label_map.get(str(top_class), "artificial" if artificial_prob > human_prob else "human")

        findings = []
        findings.append(
            f"Swin Transformer classifier [{_MODEL_NAME}]: "
            f"artificial={artificial_prob:.1%}, human={human_prob:.1%}"
        )
        if artificial_prob > 0.7:
            findings.append("Strong AI-generation signal from deep features.")
        elif human_prob > 0.7:
            findings.append("Strong real-camera signal from deep features.")
        findings.append(f"Top prediction: '{top_label}' (conf: {confidence:.1%})")

        # Extract top-2 logits for details
        logit_vals = logits.cpu().numpy()[0].tolist()

        return TestResult(
            name="Deep Learning Detector (Swin Transformer)",
            score=round(ai_score, 1),
            confidence=round(confidence, 4),
            explanation="; ".join(findings),
            details={
                "model": _MODEL_NAME,
                "architecture": "SwinTransformer",
                "ai_class_index": int(ai_index),
                "real_class_index": int(real_index),
                "label_map": _json_safe(label_map),
                "artificial_prob": round(artificial_prob, 6),
                "human_prob": round(human_prob, 6),
                "logits": logit_vals,
                "top_label": top_label,
            },
        )
    except Exception as exc:
        return TestResult(
            name="Deep Learning Detector (Swin Transformer)",
            score=50.0,
            confidence=0.0,
            explanation=f"Deep learning inference failed: {exc}",
            details={"model": _MODEL_NAME, "error": str(exc)},
        )


# ════════════════════════════════════════════════════════════════════════════
#  Test 3.5 — Error Level Analysis (ELA)
# ════════════════════════════════════════════════════════════════════════════

def _run_ela(cv_img: np.ndarray, quality: int = 95) -> tuple[np.ndarray, float]:
    """Run Error Level Analysis (ELA) on an image.

    ELA works by re-encoding the image at a lower JPEG quality and
    comparing the difference.  Areas that were modified or
    synthesised (common in AI images) show different error levels
    than naturally captured regions.

    Returns ``(ela_image, mean_error)`` where *ela_image* is a
    scaled 8-bit array (0–255) and *mean_error* is the average
    absolute difference.
    """
    # Convert to RGB and to PIL Image
    rgb = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(rgb)

    # Convert to RGB mode (handle RGBA, P, etc.)
    if pil_img.mode != "RGB":
        pil_img = pil_img.convert("RGB")

    orig_np = np.array(pil_img, dtype=np.float64)

    # Re-encode at lower quality
    buf = io.BytesIO()
    pil_img.save(buf, format="JPEG", quality=quality)
    buf.seek(0)
    re_encoded = Image.open(buf)
    re_np = np.array(re_encoded, dtype=np.float64)

    # Ensure same size (JPEG may round dimensions)
    if re_np.shape != orig_np.shape:
        re_np = np.array(re_encoded.resize(pil_img.size), dtype=np.float64)

    # Compute difference
    diff = np.abs(orig_np - re_np)
    max_diff = diff.max() if diff.max() > 0 else 1.0
    ela_image = (diff / max_diff) * 255.0
    ela_image = np.clip(ela_image, 0, 255).astype(np.uint8)
    mean_error = float(diff.mean())

    return ela_image, mean_error


def test_error_level_analysis(cv_img: np.ndarray) -> TestResult:
    """Run Error Level Analysis (ELA) as a forensic test.

    ELA re-encodes the image at a lower JPEG quality and measures the
    difference.  In real photographs, natural compression artefacts
    vary smoothly.  In AI-generated images, the error levels are
    often *too uniform* (because the generator produces the image
    in one pass) or show *abrupt boundaries* (where elements were
    pasted/composited).

    The score is derived from:
      • Mean absolute error (higher = more recompression artefacts)
      • Std-dev of the error (lower = more uniform = suspicious)
      • Presence of block-level boundaries at regular intervals
    """
    findings: list[str] = []
    details: dict[str, Any] = {}
    ai_prob = 50.0
    confidence = 0.5

    try:
        ela_img, mean_error = _run_ela(cv_img, quality=95)

        h, w = ela_img.shape[:2]
        ela_gray = cv2.cvtColor(ela_img, cv2.COLOR_RGB2GRAY) if ela_img.ndim == 3 else ela_img
        ela_std = float(np.std(ela_gray.astype(np.float64)))
        ela_mean = float(np.mean(ela_gray.astype(np.float64)))
        details["ela_mean_error"] = round(ela_mean, 4)
        details["ela_std"] = round(ela_std, 4)
        details["max_error"] = round(float(ela_img.max()), 4)

        findings.append(f"ELA mean error: {ela_mean:.2f} (quality=95); std={ela_std:.2f}")

        # --- Recalibrated ELA scoring ---
        # Recombination error that is unusually *uniform* across the image
        # (low spatial variance / low block-level CV) is a strong AI signal:
        # a generator produces a globally-coherent image, so re-encoding it
        # to JPEG introduces compression error that is far flatter than the
        # naturally regionally-varying error of a real camera JPEG.
        #
        # Block-level (8×8) CV is the primary signal; the global std and the
        # minimal-error case are secondary guards.  The previous thresholds
        # left a dead zone (std ~8-15, block CV ~0.05-0.10) that pinned both
        # real and synthetic images to 50%; the recalibration below makes ELA
        # actively discriminate instead.

        # 1. Global error uniformity (low std = synthetic)
        if ela_std < 7.0:
            findings.append(
                "Very uniform ELA error distribution (low std) — "
                "characteristic of AI-generated / synthetic images."
            )
            ai_prob = max(ai_prob, 68.0)
            confidence = max(confidence, 0.68)

        # 2. Block-level (8×8 JPEG blocks) uniformity — strongest signal.
        #    Real JPEGs show regionally-varying block errors (high CV);
        #    synthetic images show uniform block errors (low CV).
        gray_ela = ela_gray.astype(np.float64)
        block_size = 8
        bh, bw = h // block_size, w // block_size
        if bh > 4 and bw > 4:
            trimmed = gray_ela[:bh*block_size, :bw*block_size]
            blocks = trimmed.reshape(bh, block_size, bw, block_size).mean(axis=(1, 3))
            block_std = float(np.std(blocks))
            block_mean = float(np.mean(blocks))
            block_cv = block_std / (block_mean + 1e-8)
            details["ela_block_std"] = round(block_std, 4)
            details["ela_block_cv"] = round(block_cv, 4)
            findings.append(f"Block-level (8×8) ELA std={block_std:.2f}, CV={block_cv:.3f}")

            if block_mean > 2.0:
                if block_cv < 0.10:
                    findings.append(
                        "Uniform block-level ELA errors (CV<0.10) — synthetic "
                        "compression pattern characteristic of AI generation."
                    )
                    ai_prob = max(ai_prob, 70.0)
                    confidence = max(confidence, 0.70)
                elif block_cv < 0.22:
                    findings.append(
                        "Below-average block-level ELA variation — compression "
                        "artefacts unusually uniform (AI-leaning)."
                    )
                    ai_prob = max(ai_prob, 60.0)
                    confidence = max(confidence, 0.60)
                elif block_cv > 0.40:
                    findings.append(
                        "Block-level ELA varies naturally — consistent with real "
                        "camera JPEG recompression."
                    )
                    ai_prob = min(ai_prob, 34.0)
                    confidence = max(confidence, 0.65)

        # Very low overall error = image was likely not JPEG-compressed naturally
        if ela_mean < 1.0:
            findings.append("Minimal ELA error — image may have been saved at high quality (common for PNGs from AI tools).")
            ai_prob = max(ai_prob, 55.0)
            confidence = max(confidence, 0.55)

        details["ela_image_shape"] = [int(h), int(w)]
        details["ela_image_size"] = int(ela_img.nbytes)

    except Exception as exc:
        findings.append(f"ELA analysis error: {exc}")
        ai_prob = 50.0
        confidence = 0.0
        details["error"] = str(exc)

    details["test_type"] = "ela"

    # Determine verdict for individual test
    if ai_prob < UNCERTAIN_LOW:
        test_verdict = "Real Camera Photo"
    elif ai_prob <= AI_THRESHOLD:
        test_verdict = "Uncertain / Mixed Signals"
    else:
        test_verdict = "AI-Generated"

    return TestResult(
        name="Error Level Analysis (ELA)",
        score=round(ai_prob, 1),
        confidence=round(confidence, 4),
        explanation="; ".join(findings),
        details=details,
    )


# ════════════════════════════════════════════════════════════════════════════
#  Test 3 — Frequency Domain Analysis (Enhanced 2D FFT)
# ════════════════════════════════════════════════════════════════════════════

def test_frequency(cv_img: np.ndarray) -> TestResult:
    """
    Analyse the image in the frequency domain (via FFT).

    Recalibrated v2:
      • Normalised thresholds — textured surfaces (skin, fabric, hair,
        foliage) naturally have high HF content; only *extreme* cases are flagged
      • Natural 1/f² fall-off is a strong REAL signal
    """
    findings: list[str] = []
    details: dict[str, Any] = {}
    ai_prob = 50.0
    confidence = 0.5

    gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY).astype(np.float64)
    h, w = gray.shape

    # Compute 2D FFT
    gray_norm = gray - np.mean(gray)
    fft = np.fft.fft2(gray_norm)
    fft_shift = np.fft.fftshift(fft)
    magnitude = np.abs(fft_shift)
    magnitude = np.log1p(magnitude)

    # --- Radial frequency profile ---
    center = (h // 2, w // 2)
    max_radius = min(h, w) // 2

    radial_profiles = []
    for r in range(1, max_radius, 3):
        y, x = np.ogrid[:h, :w]
        dist = np.sqrt((x - center[1]) ** 2 + (y - center[0]) ** 2)
        ring = (dist >= r) & (dist < r + 3)
        ring_vals = magnitude[ring]
        radial_profiles.append(float(np.mean(ring_vals)) if ring_vals.size > 0 else 0.0)

    radial_profile = np.array(radial_profiles)
    if len(radial_profile) > 1:
        radial_profile = radial_profile / (radial_profile[0] + 1e-12)

    # --- Spectral slope ---
    radii = np.arange(1, len(radial_profile) + 1)
    log_radii = np.log(radii[radii > 0])
    log_power = np.log(radial_profile[radii > 0] + 1e-12)

    if len(log_radii) > 3:
        coeffs = np.polyfit(log_radii, log_power, 1)
        slope = float(coeffs[0])
        details["spectral_slope"] = round(slope, 3)

        if slope > 0.5:
            findings.append(
                f"Frequency spectrum is very flat (slope={slope:.2f}). "
                f"Natural images typically fall off as ~1/f^2 (slope ~ -2)."
            )
            ai_prob = min(95.0, ai_prob + 30.0)
            confidence = max(confidence, 0.7)
        elif slope > 0.0:
            findings.append(f"Spectral slope is shallow (slope={slope:.2f}), somewhat AI-like.")
            ai_prob = min(95.0, ai_prob + 12.0)
            confidence = max(confidence, 0.5)
        elif slope > -1.2:
            findings.append(f"Spectral slope ({slope:.2f}) is moderately natural.")
            confidence = max(confidence, 0.35)
        else:
            findings.append(f"Spectral slope ({slope:.2f}) is natural, consistent with real photography.")
            ai_prob = max(15.0, ai_prob - 25.0)
            confidence = max(confidence, 0.7)
    else:
        slope = 0.0
        details["spectral_slope"] = None

    # --- High-frequency energy ---
    total_energy = np.sum(magnitude) + 1e-12
    high_freq_threshold = int(max_radius * 0.6)
    freq_grid = np.sqrt(
        (np.arange(h).reshape(-1, 1) - center[0]) ** 2
        + (np.arange(w).reshape(1, -1) - center[1]) ** 2
    )
    high_freq_mask = freq_grid > high_freq_threshold
    high_freq_energy = np.sum(magnitude[high_freq_mask])
    hf_ratio = float(high_freq_energy / total_energy)
    details["high_freq_ratio"] = round(hf_ratio, 4)

    if hf_ratio > 0.85:
        findings.append(
            f"Extremely high-frequency energy ({hf_ratio:.2%}). "
            f"This is a strong indicator of AI synthesis or severe over-sharpening."
        )
        ai_prob = min(95.0, ai_prob + 20.0)
        confidence = max(confidence, 0.55)
    elif hf_ratio > 0.70:
        findings.append(
            f"Very high-frequency energy ({hf_ratio:.2%}). "
            f"May indicate AI generation or over-sharpening."
        )
        ai_prob = min(95.0, ai_prob + 5.0)
        confidence = max(confidence, 0.50)
    elif hf_ratio > 0.45:
        findings.append(f"Moderately high high-frequency content ({hf_ratio:.2%}). Could be textured surfaces.")
        ai_prob = min(95.0, ai_prob + 2.0)
        confidence = max(confidence, 0.30)
    elif hf_ratio < 0.12:
        findings.append(f"Low high-frequency energy ({hf_ratio:.2%}), consistent with lens softness or natural fall-off.")
        ai_prob = max(20.0, ai_prob - 12.0)
        confidence = max(confidence, 0.5)
    else:
        findings.append(f"High-frequency content ({hf_ratio:.2%}) is within normal bounds for natural photographs.")
        ai_prob = max(28.0, ai_prob - 8.0)
        confidence = max(confidence, 0.45)

    # --- Periodicity ---
    periodicity_score = _detect_periodicity(magnitude, center)
    details["periodicity_score"] = round(periodicity_score, 4)

    if periodicity_score > 0.5:
        findings.append(
            f"Regular periodic patterns detected in frequency domain "
            f"(score={periodicity_score:.2f}). This can indicate AI generation "
            f"(patch-based training artefacts)."
        )
        ai_prob = min(95.0, ai_prob + 20.0)
        confidence = max(confidence, 0.6)

    # --- Spectral flatness (spectral whiteness) ---
    # AI images often have flatter spectra (less 1/f decay) — the geometric
    # mean approaches the arithmetic mean.  Natural images have a steep
    # 1/f^2 fall-off, giving a low spectral flatness.
    nonzero_mag = magnitude[magnitude > 0.01]
    if len(nonzero_mag) > 10:
        # Use log-space for numerical stability
        log_mag = np.log(nonzero_mag)
        geo_mean = float(np.exp(np.mean(log_mag)))
        arith_mean = float(np.mean(nonzero_mag))
        spectral_flatness = geo_mean / (arith_mean + 1e-12)
        details["spectral_flatness"] = round(spectral_flatness, 4)

        if spectral_flatness > 0.15:
            findings.append(
                f"Spectrum is unusually flat (flatness={spectral_flatness:.3f}). "
                f"Natural images have steep 1/f decay."
            )
            ai_prob = min(95.0, ai_prob + 15.0)
            confidence = max(confidence, 0.55)

    # --- Radial energy distribution ---
    # Natural images concentrate energy at low frequencies; AI images may
    # show more uniform spread across frequency bands.
    if len(radial_profile) > 2:
        # Energy in first third of frequencies (low freq) vs last third (high freq)
        n = len(radial_profile)
        low_energy = np.sum(radial_profile[:n // 3]) if n >= 3 else 0.0
        high_energy = np.sum(radial_profile[2 * n // 3:]) if n >= 3 else 0.0
        low_ratio = float(low_energy / (low_energy + high_energy + 1e-12))
        details["low_freq_ratio"] = round(low_ratio, 4)

        if low_ratio < 0.40:
            findings.append(
                f"Low-frequency energy is low ({low_ratio:.1%}). "
                f"Natural images concentrate most energy at low frequencies."
            )
            ai_prob = min(95.0, ai_prob + 10.0)
            confidence = max(confidence, 0.50)

    explanation = "; ".join(findings)
    return TestResult(
        name="Frequency Domain Analysis",
        score=ai_prob,
        confidence=confidence,
        explanation=explanation,
        details=details,
    )


def _detect_periodicity(magnitude: np.ndarray, center: tuple) -> float:
    """Detect grid-like periodic patterns using scipy find_peaks."""
    try:
        from scipy.signal import find_peaks

        h, w = magnitude.shape
        if h < 100 or w < 100:
            return 0.0

        cx, cy = int(center[1]), int(center[0])

        # Horizontal profile (skip DC)
        h_profile = magnitude[cy, :].copy()
        half_w = min(w // 12, 30)
        h_profile[max(0, cx - half_w):cx + half_w] = 0

        # Vertical profile (skip DC)
        v_profile = magnitude[:, cx].copy()
        half_h = min(h // 12, 30)
        v_profile[max(0, cy - half_h):cy + half_h] = 0

        def _analyse_profile(profile: np.ndarray) -> float:
            if np.std(profile) < 1e-10:
                return 0.0

            profile = profile / (np.max(profile) + 1e-12)
            threshold = np.mean(profile) + 1.5 * np.std(profile)
            min_dist = max(int(len(profile) / 20), 5)
            peaks, props = find_peaks(profile, height=threshold, distance=min_dist)

            if len(peaks) < 2:
                return 0.0

            spacings = np.diff(peaks).astype(float)
            mean_sp = float(np.mean(spacings))
            if mean_sp < 2:
                return 0.0

            std_sp = float(np.std(spacings))
            regularity = 1.0 - min(1.0, std_sp / mean_sp)
            avg_peak_height = float(np.mean(props["peak_heights"]))
            peak_density = min(1.0, len(peaks) / 5.0)

            return min(1.0, regularity * avg_peak_height * peak_density)

        return float((_analyse_profile(h_profile) + _analyse_profile(v_profile)) / 2.0)
    except Exception:
        return 0.0


# ════════════════════════════════════════════════════════════════════════════
#  Test 4 — Statistical Analysis
# ════════════════════════════════════════════════════════════════════════════

def test_statistics(cv_img: np.ndarray) -> TestResult:
    """
    Statistical tests on pixel-level distributions.

    Recalibrated v2:
      • Channel correlation 0.90–0.98 is **normal** for real photos
        (only > 0.98 is suspicious)
      • JPEG compression naturally reduces entropy — not anomalous
      • Double-JPEG is common (social media re-encodes) — reduced penalty
    """
    findings: list[str] = []
    details: dict[str, Any] = {}
    ai_prob = 50.0
    confidence = 0.5

    gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape
    total_pixels = h * w

    # --- Histogram entropy ---
    hist, _ = np.histogram(gray.flatten(), bins=256, range=(0, 255))
    hist_norm = hist / (total_pixels + 1e-12)
    hist_norm = hist_norm[hist_norm > 0]
    entropy = float(-np.sum(hist_norm * np.log2(hist_norm)))
    max_entropy = 8.0
    normalized_entropy = entropy / max_entropy

    details["histogram_entropy"] = round(entropy, 4)
    details["normalized_entropy"] = round(normalized_entropy, 4)

    if normalized_entropy < 0.50:
        findings.append(
            f"Very low histogram entropy ({normalized_entropy:.2%}). "
            f"May indicate posterisation from AI or heavy compression."
        )
        ai_prob = min(80.0, ai_prob + 15.0)
        confidence = max(confidence, 0.5)
    elif normalized_entropy < 0.65:
        findings.append(f"Low-ish entropy ({normalized_entropy:.2%}) — could be JPEG compression, not necessarily AI.")
        ai_prob = ai_prob + 5.0
        confidence = max(confidence, 0.3)
    else:
        findings.append(f"Histogram entropy ({normalized_entropy:.2%}) is healthy (neutral signal).")
        # High entropy is neutral — both real photos and AI images can have high entropy
        confidence = max(confidence, 0.2)

    # --- Channel correlation ---
    b, g, r = cv2.split(cv_img)
    b_flat = b.astype(np.float64).flatten()
    g_flat = g.astype(np.float64).flatten()
    r_flat = r.astype(np.float64).flatten()

    bg_corr = float(np.corrcoef(b_flat, g_flat)[0, 1])
    br_corr = float(np.corrcoef(b_flat, r_flat)[0, 1])
    gr_corr = float(np.corrcoef(g_flat, r_flat)[0, 1])
    avg_channel_corr = (abs(bg_corr) + abs(br_corr) + abs(gr_corr)) / 3.0

    details["channel_correlation"] = round(avg_channel_corr, 4)
    details["channel_correlations"] = {
        "B-G": round(bg_corr, 4), "B-R": round(br_corr, 4), "G-R": round(gr_corr, 4),
    }

    if avg_channel_corr > 0.99:
        findings.append(
            f"Extremely high inter-channel correlation (r={avg_channel_corr:.4f}). "
            f"This is unusually high and can indicate AI synthesis."
        )
        ai_prob = min(95.0, ai_prob + 25.0)
        confidence = max(confidence, 0.7)
    elif avg_channel_corr > 0.97:
        findings.append(f"Very high channel correlation (r={avg_channel_corr:.4f}), moderately suspicious.")
        ai_prob = min(95.0, ai_prob + 10.0)
        confidence = max(confidence, 0.5)
    elif avg_channel_corr > 0.95:
        findings.append(f"Channel correlation ({avg_channel_corr:.4f}) is on the high side.")
        ai_prob = ai_prob + 3.0
        confidence = max(confidence, 0.3)
    else:
        findings.append(f"Channel correlation ({avg_channel_corr:.4f}) is normal for real photographs.")
        ai_prob = max(15.0, ai_prob - 10.0)
        confidence = max(confidence, 0.4)

    # --- Kurtosis ---
    gray_flat = gray.astype(np.float64).flatten()
    kurt = float(((gray_flat - np.mean(gray_flat)) ** 4).mean() / (np.var(gray_flat) ** 2 + 1e-12))
    excess_kurtosis = kurt - 3.0
    details["excess_kurtosis"] = round(excess_kurtosis, 4)

    if excess_kurtosis > 6.0:
        findings.append(
            f"High excess kurtosis ({excess_kurtosis:.2f}). "
            f"Pixel distribution has very heavy tails."
        )
        ai_prob = min(95.0, ai_prob + 10.0)
        confidence = max(confidence, 0.45)

    # --- Double JPEG ---
    double_jpeg_score = _check_double_jpeg(gray)
    details["double_jpeg"] = round(double_jpeg_score, 4)

    if double_jpeg_score > 0.9:
        findings.append("Strong double-JPEG compression detected (common with re-saved images).")
        ai_prob = min(95.0, ai_prob + 2.0)
        confidence = max(confidence, 0.20)

    explanation = "; ".join(findings)
    return TestResult(
        name="Statistical Analysis",
        score=ai_prob,
        confidence=confidence,
        explanation=explanation,
        details=details,
    )


def _check_double_jpeg(gray: np.ndarray) -> float:
    """Detect double JPEG compression via 8x8 block boundary analysis."""
    try:
        h, w = gray.shape
        if h < 128 or w < 128:
            return 0.0

        block_size = 8
        diff_h = np.abs(np.diff(gray[::block_size, :].astype(np.float64), axis=0))
        diff_v = np.abs(np.diff(gray[:, ::block_size].astype(np.float64), axis=1))

        block_boundary_strength = float(np.mean(diff_h) + np.mean(diff_v)) / 2.0
        global_gradient = float(np.mean(np.abs(np.diff(gray.astype(np.float64)))))
        if global_gradient < 1e-8:
            return 0.0

        return min(1.0, block_boundary_strength / global_gradient)
    except Exception:
        return 0.0


# ════════════════════════════════════════════════════════════════════════════
#  Test 5 — Visual Artifact Detection
# ════════════════════════════════════════════════════════════════════════════

def test_artifacts(cv_img: np.ndarray) -> TestResult:
    """
    Look for visual artefacts common in AI-generated images.

    Recalibrated v2:
      • Smooth portraits / HDR photos are **not** suspicious
      • Only flag *extreme* over-smoothing with *additional* AI signals
      • Natural textures (fabric, skin, foliage) are rewarded as REAL
    """
    findings: list[str] = []
    details: dict[str, Any] = {}
    ai_prob = 50.0
    confidence = 0.5

    gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape

    # --- High-frequency detail ---
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    hf_content = gray.astype(np.float64) - blurred.astype(np.float64)
    hf_energy = float(np.sum(hf_content ** 2))
    total_energy = float(np.sum(gray.astype(np.float64) ** 2)) + 1e-12
    hf_ratio = hf_energy / total_energy
    details["high_freq_detail_ratio"] = round(hf_ratio, 6)

    if hf_ratio < 0.0005:
        findings.append(
            f"Very low high-frequency detail ({hf_ratio:.4%}). "
            f"Image appears significantly over-smoothed — common in AI output."
        )
        ai_prob = min(95.0, ai_prob + 25.0)
        confidence = max(confidence, 0.7)
    elif hf_ratio < 0.002:
        findings.append(f"Low high-frequency detail ({hf_ratio:.4%}), somewhat over-smoothed.")
        ai_prob = min(95.0, ai_prob + 8.0)
        confidence = max(confidence, 0.4)
    else:
        findings.append(f"Normal high-frequency detail ({hf_ratio:.4%}), consistent with textural variation in real photos.")
        ai_prob = max(10.0, ai_prob - 20.0)
        confidence = max(confidence, 0.6)

    # --- Symmetry ---
    left_half = gray[:, :w // 2]
    right_half = gray[:, w - w // 2:][:, ::-1]
    min_w = min(left_half.shape[1], right_half.shape[1])
    symmetry_score = float(np.mean(np.abs(
        left_half[:, :min_w].astype(np.float64) - right_half[:, :min_w].astype(np.float64)
    )))
    max_val = float(max(np.max(left_half), np.max(right_half), 1))
    normalized_symmetry = symmetry_score / (max_val + 1e-8)
    details["symmetry_score"] = round(normalized_symmetry, 4)

    # Only flag symmetry when combined with low detail (both = strong AI signal)
    if normalized_symmetry < 0.10 and hf_ratio < 0.002:
        findings.append(
            f"High symmetry (score={normalized_symmetry:.3f}) combined with low detail "
            f"— characteristic of AI generation."
        )
        ai_prob = min(95.0, ai_prob + 18.0)
        confidence = max(confidence, 0.55)

    # --- Edge density ---
    edges = cv2.Canny(gray, 50, 150)
    edge_density = float(np.sum(edges > 0)) / (h * w)
    details["edge_density"] = round(edge_density, 4)

    if edge_density < 0.01:
        findings.append(f"Very low edge density ({edge_density:.2%}). AI images often lack fine detail.")
        ai_prob = min(95.0, ai_prob + 10.0)
        confidence = max(confidence, 0.45)
    elif edge_density > 0.25:
        findings.append(f"High edge density ({edge_density:.2%}) could indicate over-sharpening.")
        ai_prob = min(95.0, ai_prob + 4.0)
        confidence = max(confidence, 0.30)
    else:
        findings.append(f"Edge density ({edge_density:.2%}) is within normal bounds for photographs.")
        ai_prob = max(15.0, ai_prob - 8.0)
        confidence = max(confidence, 0.4)

    # --- Texture variance ---
    texture_variance = _texture_analysis(gray)
    details["texture_variance"] = round(texture_variance, 4)

    if texture_variance < 200.0:
        findings.append(
            f"Low texture variance ({texture_variance:.1f}). "
            f"Image lacks micro-texture detail typical of real photographs."
        )
        ai_prob = min(95.0, ai_prob + 15.0)
        confidence = max(confidence, 0.5)
    elif texture_variance > 2000.0:
        findings.append(f"Healthy texture variance ({texture_variance:.1f}), consistent with real photographic detail.")
        ai_prob = max(10.0, ai_prob - 15.0)
        confidence = max(confidence, 0.6)
    else:
        findings.append(f"Texture variance ({texture_variance:.1f}) is moderate.")
        ai_prob = max(15.0, ai_prob - 3.0)

    # --- Text & Grid Anomaly Detection ---
    anomaly_score, anomaly_details = _detect_text_grid_anomalies(cv_img)
    details.update(anomaly_details)

    if anomaly_score > 0:
        if anomaly_score >= 40:
            findings.append(
                f"Strong text/grid anomalies detected ({anomaly_score:.0f} pts): "
                f"large smooth white background with hyper-uniform texture "
                f"and periodic patterns — characteristic of AI-generated "
                f"notebook pages, diagrams, or text renders."
            )
            ai_prob = min(95.0, ai_prob + int(anomaly_score))
            confidence = max(confidence, 0.8)
        elif anomaly_score >= 15:
            findings.append(
                f"Mild text/grid anomalies detected ({anomaly_score:.0f} pts): "
                f"smooth backgrounds and mild periodicity — common in "
                f"synthetic text/diagrams."
            )
            ai_prob = min(95.0, ai_prob + int(anomaly_score * 0.7))
            confidence = max(confidence, 0.6)

    explanation = "; ".join(findings)
    return TestResult(
        name="Visual Artifact Detection",
        score=ai_prob,
        confidence=confidence,
        explanation=explanation,
        details=details,
    )


def _texture_analysis(gray: np.ndarray) -> float:
    """Quick texture analysis using local variance of the Laplacian."""
    try:
        lap = cv2.Laplacian(gray, cv2.CV_64F)
        h, w = lap.shape
        step = 32
        variances = []
        for i in range(0, h - step, step):
            for j in range(0, w - step, step):
                block = lap[i:i + step, j:j + step]
                variances.append(float(np.var(block)))
        return float(np.mean(variances)) if variances else 0.0
    except Exception:
        return 0.0


# ════════════════════════════════════════════════════════════════════════════
#  Scoring Engine
# ════════════════════════════════════════════════════════════════════════════

def _sigmoid_scale(score: float, steepness: float = 0.08) -> float:
    """Apply a sigmoid (logistic) scaling curve to push extreme scores
    toward 0 or 100.

    50 maps to 50 (neutral).  Values far from 50 are amplified:
        0%  → ~1.8%
       20%  → ~8.0%
       30%  → ~15%
       40%  → ~23%
       50%  → 50%
       60%  → ~77%
       70%  → ~85%
       80%  → ~92%
       100% → ~98.2%
    """
    return max(0.0, min(100.0, 100.0 / (1.0 + math.exp(-steepness * (score - 50.0)))))


def _expand_test_score(score: float, confidence: float) -> float:
    """Expand a test's score away from 50% based on its confidence.

    High-confidence tests are pushed toward 0 or 100, making them
    more decisive in the aggregate.  Low-confidence tests stay near 50.
    """
    factor = 0.5 + confidence  # range 0.5 – 1.5
    return max(0.0, min(100.0, 50.0 + (score - 50.0) * factor))


def _determine_has_exif(tests: list[TestResult]) -> bool:
    """Check whether any metadata test found real EXIF data."""
    for t in tests:
        if t.name.lower().split()[0] in ("metadata", "c2pa"):
            exif_tag_count = t.details.get("exif_tag_count", 0)
            if exif_tag_count and exif_tag_count > 0:
                return True
            # Metadata test stores rich exif in its details
            exif_data = t.details.get("exif")
            if exif_data and len(exif_data) > 0:
                return True
    return False


def aggregate_results(
    tests: list[TestResult],
    threshold: float = 0.55,
    has_exif: bool = True,
) -> tuple[float, float, str, str]:
    """
    Combine all test results into an overall AI-probability score.

    Pipeline (v3.0):
      1. **Dynamic weighting** — if EXIF is absent, boost physical-signal
         tests (Noise, Frequency, Visual) and reduce metadata weights.
      2. **Score expansion** — each test's score is expanded away from 50
         proportionally to its confidence.
      3. **Weighted aggregation** — confidence-weighted average of
         expanded scores.
      4. **Sigmoid scaling** — final non-linear transform for stronger
         verdict confidence (extreme signals → closer to 0 / 100).
    """
    # ── 1. Dynamic weight adjustment ───────────────────────────────────
    if not has_exif:
        # Boost physical signal tests, reduce metadata tests
        weight_multipliers = DYNAMIC_WEIGHTS_NO_EXIF
    else:
        weight_multipliers = {k: 1.0 for k in TEST_WEIGHTS}

    # ── 2. Per-test score expansion ──────────────────────────────────────
    weighted_sum = 0.0
    weight_total = 0.0
    confidence_values: list[float] = []

    for test in tests:
        key = test.name.lower().split()[0]
        base_weight = TEST_WEIGHTS.get(key, 0.2)
        multiplier = weight_multipliers.get(key, 1.0)
        weight = base_weight * multiplier

        expanded_score = _expand_test_score(test.score, test.confidence)
        weighted_sum += expanded_score * weight * test.confidence
        weight_total += weight * test.confidence
        confidence_values.append(test.confidence)

    raw_score = weighted_sum / (weight_total + 1e-12) if weight_total > 0 else 50.0
    overall_confidence = float(np.mean(confidence_values))

    # ── 3 & 4. Non-linear sigmoid scaling on the aggregated score ──────
    overall_score = _sigmoid_scale(raw_score)

    # ── Verdict ────────────────────────────────────────────────────────
    if overall_score < UNCERTAIN_LOW:
        verdict = "Real Camera Photo"
    elif overall_score <= AI_THRESHOLD:
        verdict = "Uncertain / Mixed Signals"
    else:
        verdict = "AI-Generated"

    ai_tests = [t for t in tests if t.score > 50.0]
    real_tests = [t for t in tests if t.score < 50.0]

    parts = [
        f"AI Probability: {overall_score:.0f}% (Real: {100 - overall_score:.0f}%) (conf: {overall_confidence:.0%})",
    ]
    if ai_tests:
        parts.append(f"AI indicators from: {', '.join(t.name for t in ai_tests)}")
    if real_tests:
        parts.append(f"Real-photo indicators from: {', '.join(t.name for t in real_tests)}")
    parts.append(f"Verdict: {verdict}")

    summary = " | ".join(parts)

    return overall_score, overall_confidence, verdict, summary


# ════════════════════════════════════════════════════════════════════════════
#  Report Generation (Console + HTML)
# ════════════════════════════════════════════════════════════════════════════

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Image Analysis Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: #0f0f23;
            color: #e0e0e0;
            min-height: 100vh;
            padding: 20px;
        }}
        .container {{ max-width: 1000px; margin: 0 auto; }}
        h1 {{ color: #00d4ff; font-size: 2em; margin-bottom: 5px; }}
        .subtitle {{ color: #888; margin-bottom: 25px; font-size: 0.9em; }}
        .verdict {{
            display: inline-block;
            padding: 12px 30px;
            border-radius: 8px;
            font-size: 1.3em;
            font-weight: bold;
            margin-bottom: 25px;
        }}
        .verdict.AI-Generated {{ background: #8B0000; color: #ff6b6b; border: 2px solid #ff4444; }}
        .verdict.Real\\ Camera\\ Photo {{ background: #004d00; color: #66cc66; border: 2px solid #44aa44; }}
        .verdict.Uncertain\\ /\\ Mixed\\ Signals {{ background: #8B6913; color: #ffd700; border: 2px solid #e6b800; }}
        .score-bar {{
            height: 30px;
            background: linear-gradient(90deg, #004d00 0%, #00d4ff 50%, #8B0000 100%);
            border-radius: 6px;
            position: relative;
            margin-bottom: 5px;
        }}
        .score-marker {{
            position: absolute;
            top: -5px;
            width: 3px;
            height: 40px;
            background: #fff;
            transform: translateX(-50%);
        }}
        .score-label {{ text-align: center; margin-bottom: 30px; color: #aaa; }}
        .test-card {{
            background: #1a1a2e;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 15px;
            border-left: 4px solid #444;
        }}
        .test-card.AI {{ border-left-color: #ff4444; }}
        .test-card.Real {{ border-left-color: #44aa44; }}
        .test-card.Uncertain {{ border-left-color: #aaa; }}
        .test-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }}
        .test-name {{ font-size: 1.1em; font-weight: 600; }}
        .test-score {{
            font-family: monospace;
            font-size: 1.2em;
            padding: 3px 12px;
            border-radius: 4px;
            background: rgba(0,0,0,0.3);
        }}
        .test-score.positive {{ color: #ff6b6b; }}
        .test-score.negative {{ color: #66cc66; }}
        .test-score.neutral {{ color: #aaa; }}
        .explanation {{ margin: 8px 0; line-height: 1.5; color: #ccc; }}
        .details {{
            margin-top: 10px;
            padding: 10px;
            background: rgba(0,0,0,0.2);
            border-radius: 6px;
            font-family: monospace;
            font-size: 0.8em;
            max-height: 150px;
            overflow-y: auto;
        }}
        .confidence {{
            font-size: 0.85em;
            color: #888;
            margin: 5px 0 0 0;
        }}
        .footer {{ text-align: center; margin-top: 30px; color: #555; font-size: 0.8em; }}
        .image-preview {{
            max-width: 100%;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.5);
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>AI Image Analysis Report</h1>
            <p class="subtitle">
            Analysed: <strong>{image_path}</strong> ·
            Resolution: <strong>{width} x {height}</strong> ·
            File size: <strong>{file_size}</strong> ·
            Date: <strong>{timestamp}</strong>
        </p>

        <div class="verdict {verdict_class}">
            {verdict_text}
        </div>

        <div class="score-bar">
            <div class="score-marker" style="left: {score_percent}%"></div>
        </div>
        <div class="score-label">
            AI Probability: {ai_prob:.0f}% · Real Confidence: {real_prob:.0f}% · Confidence: {confidence:.0%}
        </div>

        <p style="color: #ccc; line-height: 1.6; margin-bottom: 20px;">{summary}</p>

        {test_cards}

        <div class="footer">
            AI Image Analyzer v3.1 · Educational / research use ·
            Percentage-based forensic scoring · 8 complementary tests
        </div>
    </div>
</body>
</html>
"""


def generate_html_report(report: AnalysisReport, image_path: str) -> str:
    """Generate an interactive HTML report for a single image."""
    score = report.overall_score
    score_percent = max(0, min(100, score))

    test_cards = ""
    for test in report.tests:
        verdict_class = "AI" if test.score > 55 else ("Real" if test.score < 20 else "Uncertain")
        score_class = "positive" if test.score > 55 else ("negative" if test.score < 20 else "neutral")
        ai_pct = f"{test.score:.0f}%"

        details_json = json.dumps(_json_safe(test.details), indent=2)

        test_cards += f"""
        <div class="test-card {verdict_class}">
            <div class="test-header">
                <span class="test-name">{test.name}</span>
                <span class="test-score {score_class}">AI: {ai_pct}</span>
            </div>
            <div class="confidence">Confidence: {test.confidence:.0%} · Verdict: {test.verdict}</div>
            <div class="explanation">{test.explanation}</div>
            <div class="details">{details_json}</div>
        </div>
        """

    # Read the image for preview (base64)
    img_preview = ""
    try:
        ext = os.path.splitext(image_path)[1].lower()
        mime_map = {".jpg": "jpeg", ".jpeg": "jpeg", ".png": "png",
                     ".bmp": "bmp", ".webp": "webp", ".gif": "gif"}
        mime_type = mime_map.get(ext, "jpeg")
        with open(image_path, "rb") as f:
            img_b64 = base64.b64encode(f.read()).decode()
        img_preview = f'<img class="image-preview" src="data:image/{mime_type};base64,{img_b64[:50000]}" alt="Analysed image preview">'
    except Exception:
        pass

    html = HTML_TEMPLATE.format(
        image_path=html_escape(report.image_path),
        width=report.image_size[0],
        height=report.image_size[1],
        file_size=human_readable_size(report.file_size),
        timestamp=report.timestamp,
        verdict_class=report.verdict.replace(" ", "\\ "),
        verdict_text=report.verdict,
        score_percent=score_percent,
        ai_prob=score,
        real_prob=100 - score,
        confidence=report.overall_confidence,
        summary=report.summary,
        test_cards=test_cards,
    )

    return img_preview + html


def _generate_batch_html(output_path: str, reports: list[AnalysisReport]) -> None:
    """Generate a combined HTML report for multiple images in batch mode."""
    from datetime import datetime as dt

    total = len(reports)
    ai_count = sum(1 for r in reports if r.verdict == "AI-Generated")
    uncertain_count = sum(1 for r in reports if r.verdict == "Uncertain / Mixed Signals")
    real_count = sum(1 for r in reports if r.verdict == "Real Camera Photo")

    sections = []
    for i, report in enumerate(reports, 1):
        single_html = generate_html_report(report, report.image_path)
        sections.append(f'<div class="batch-section" id="img-{i}">\n{single_html}\n</div>')

    batch_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Image Analysis — Batch Report ({total} images)</title>
    <style>
        body {{ font-family: sans-serif; background: #0f0f23; color: #e0e0e0; }}
        .header {{
            background: #1a1a2e; padding: 20px; border-bottom: 2px solid #00d4ff;
            text-align: center;
        }}
        .summary-bar {{
            display: flex; gap: 10px; justify-content: center; margin: 20px 0;
        }}
        .summary-card {{
            background: #1a1a2e; border-radius: 10px; padding: 15px 30px; text-align: center;
            border: 1px solid #444;
        }}
        .summary-card .count {{ font-size: 2em; font-weight: bold; }}
        .summary-card .label {{ font-size: 0.85em; color: #888; }}
        .summary-card.ai .count {{ color: #ff6b6b; }}
        .summary-card.real .count {{ color: #66cc66; }}
        .summary-card.unc .count {{ color: #ffd700; }}
        .batch-section {{ margin-bottom: 40px; border-bottom: 1px solid #333; padding-bottom: 30px; }}
        .batch-nav {{ text-align: center; margin: 20px 0; }}
        .batch-nav a {{
            color: #00d4ff; margin: 0 10px; text-decoration: none;
        }}
        .batch-nav a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>AI Image Analysis — Batch Report</h1>
        <p>Scanned {total} images on {dt.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
    <div class="summary-bar">
        <div class="summary-card ai">
            <div class="count">{ai_count}</div>
            <div class="label">AI-Generated</div>
        </div>
        <div class="summary-card unc">
            <div class="count">{uncertain_count}</div>
            <div class="label">Uncertain</div>
        </div>
        <div class="summary-card real">
            <div class="count">{real_count}</div>
            <div class="label">Real Camera</div>
        </div>
    </div>
    <div class="batch-nav">
        {''.join(f'<a href="#img-{i}">Image {i}</a>' for i in range(1, total + 1))}
    </div>
    {''.join(sections)}
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(batch_html)


# ════════════════════════════════════════════════════════════════════════════
#  Console Output
# ════════════════════════════════════════════════════════════════════════════

def print_report(report: AnalysisReport, verbose: bool = True, quiet: bool = False,
                 no_color: bool = False) -> None:
    """Print the analysis report to the console."""
    if quiet:
        print(report.verdict)
        return

    # Choose markers
    if no_color:
        ai_marker = "[AI]"
        real_marker = "[REAL]"
        uncertain_marker = "[?]"
    else:
        ai_marker = "🔴"
        real_marker = "🟢"
        uncertain_marker = "🟡"

    width, height = report.image_size
    ai_pct = report.overall_score
    real_pct = 100.0 - ai_pct

    print()
    print("=" * 70)
    print(f"  AI IMAGE ANALYSIS REPORT")
    print("=" * 70)
    print(f"  File:        {report.image_path}")
    print(f"  Resolution:  {width} x {height}")
    print(f"  File size:   {human_readable_size(report.file_size)}")
    print(f"  Timestamp:   {report.timestamp}")
    print("=" * 70)

    # Score bar (0-100 % scale)
    bar_length = 40
    filled = int(ai_pct / 100.0 * bar_length)
    bar = "#" * filled + "-" * (bar_length - filled)
    print(f"\n  AI Probability:   {ai_pct:.1f}%")
    print(f"  Real Confidence:  {real_pct:.1f}%")
    print(f"  (Overall Conf:   {report.overall_confidence:.0%})")
    print(f"  [0% REAL{'':>22}100% AI]")
    print(f"  [{bar}]")
    print(f"\n  VERDICT: {report.verdict}")
    print("=" * 70)

    if verbose:
        print(f"\n  Per-Test Breakdown:\n")
        for test in report.tests:
            marker = real_marker if test.score < 20 else (ai_marker if test.score > 55 else uncertain_marker)
            real_p = 100.0 - test.score
            print(f"  {marker} {test.name}: AI={test.score:.0f}% | Real={real_p:.0f}% "
                  f"(conf: {test.confidence:.0%}, verdict: {test.verdict})")
            print(f"       -> {test.explanation}")
            print()

    print(f"  Summary: {report.summary}")
    print("=" * 70)
    print()


def print_batch_summary(reports: list[AnalysisReport], no_color: bool = False,
                        threshold: float = 0.65) -> None:
    """Print a summary table of batch analysis results."""
    if not reports:
        print("No images found to analyse.")
        return

    sorted_reports = sorted(reports, key=lambda r: r.overall_score, reverse=True)

    name_w = min(55, max(len("File"), max(len(os.path.basename(r.image_path)) for r in sorted_reports) + 2))
    ai_w = 10
    real_w = 10
    verdict_w = 24

    print()
    print("=" * (name_w + ai_w + real_w + verdict_w + 8))
    print(f"  {'File':<{name_w}}  {'AI %':>{ai_w}}  {'Real %':>{real_w}}  {'Verdict':<{verdict_w}}")
    print("=" * (name_w + ai_w + real_w + verdict_w + 8))

    counts: dict[str, int] = {}
    for r in sorted_reports:
        fname = os.path.basename(r.image_path)
        if len(fname) > name_w - 2:
            fname = fname[:name_w - 5] + "..."
        verdict = r.verdict
        counts[verdict] = counts.get(verdict, 0) + 1

        ai_pct = f"{r.overall_score:.0f}%"
        real_pct = f"{100 - r.overall_score:.0f}%"
        print(f"  {fname:<{name_w}}  {ai_pct:>{ai_w}}  {real_pct:>{real_w}}  {verdict:<{verdict_w}}")

    print("-" * (name_w + ai_w + real_w + verdict_w + 8))

    print(f"\n  Total images analysed: {len(reports)}")
    for verdict, count in sorted(counts.items(), key=lambda x: -x[1]):
        pct = count / len(reports) * 100
        print(f"  {verdict}: {count} ({pct:.0f}%)")

    most_suspicious = sorted_reports[0]
    if most_suspicious.overall_score > 20:
        print(f"\n  Most suspicious: {os.path.basename(most_suspicious.image_path)} "
              f"(AI probability: {most_suspicious.overall_score:.0f}%)")

    print()
    print("=" * (name_w + ai_w + real_w + verdict_w + 8))


# ════════════════════════════════════════════════════════════════════════════
#  Main Analysis Pipeline
# ════════════════════════════════════════════════════════════════════════════

def analyze_image(image_path: str, threshold: float = 0.55) -> AnalysisReport:
    """Run the full forensic analysis pipeline on an image."""
    cv_img, pil_img, exif_dict = load_image(image_path)
    h, w = cv_img.shape[:2]

    file_size = os.path.getsize(image_path)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    tests = []
    tests.append(test_metadata(pil_img, exif_dict))
    tests.append(test_c2pa_exif(image_path, pil_img, exif_dict))
    tests.append(test_noise(cv_img))
    tests.append(test_frequency(cv_img))
    tests.append(test_statistics(cv_img))
    tests.append(test_artifacts(cv_img))
    tests.append(test_deep_learning(cv_img))
    tests.append(test_error_level_analysis(cv_img))

    has_exif = bool(exif_dict) or _determine_has_exif(tests)
    overall_score, overall_confidence, verdict, summary = aggregate_results(
        tests, threshold=threshold, has_exif=has_exif
    )

    return AnalysisReport(
        image_path=image_path,
        image_size=(w, h),
        file_size=file_size,
        timestamp=timestamp,
        tests=tests,
        overall_score=overall_score,
        overall_confidence=overall_confidence,
        verdict=verdict,
        summary=summary,
    )


# ════════════════════════════════════════════════════════════════════════════
#  Batch Processing Helpers
# ════════════════════════════════════════════════════════════════════════════

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".gif", ".tiff", ".tif"}


def find_images(directory: str, recursive: bool = False) -> list[str]:
    """Find all supported image files in a directory."""
    pattern = "**/*" if recursive else "*"
    files = glob.glob(os.path.join(directory, pattern), recursive=recursive)
    return sorted(
        f for f in files
        if os.path.isfile(f) and os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
    )


# ════════════════════════════════════════════════════════════════════════════
#  CLI Entry Point
# ════════════════════════════════════════════════════════════════════════════

def main():
    """Command-line entry point."""
    # Ensure UTF-8 output on Windows consoles
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except AttributeError:
        pass

    parser = argparse.ArgumentParser(
        prog="ai_image_analyzer",
        description="Detect AI-generated images using multiple forensic techniques.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s photo.jpg                             Analyse a single image
  %(prog)s image.png --verbose                   Detailed per-test report
  %(prog)s image.jpg --json > out.json           Machine-readable JSON
  %(prog)s image.jpg --html report.html          Interactive HTML report
  %(prog)s my_photos/ --batch --summary          Scan a folder (summary only)
  %(prog)s my_photos/ --batch --recursive --html batch.html
        """,
    )
    parser.add_argument("image_path", help="Path to an image file or (with --batch) a directory")
    parser.add_argument("--batch", action="store_true",
                        help="Batch mode: scan all images in the given directory")
    parser.add_argument("--recursive", action="store_true",
                        help="Search subdirectories in batch mode (implies --batch)")
    parser.add_argument("--summary", action="store_true",
                        help="In batch mode, print only the summary table")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")
    parser.add_argument("--html", metavar="FILE", help="Write an interactive HTML report to FILE")
    parser.add_argument("-v", "--verbose", action="store_true", help="Print detailed findings for every test")
    parser.add_argument("-q", "--quiet", action="store_true", help="Print only the final verdict")
    parser.add_argument("--no-color", action="store_true", help="Disable emoji output (for plain-text terminals)")
    parser.add_argument("--threshold", type=float, default=0.55,
                        help="AI-probability threshold for verdict (0.0-1.0, default 0.55)")

    args = parser.parse_args()

    # --recursive implies --batch
    if args.recursive:
        args.batch = True

    # ── Batch Mode ───────────────────────────────────────────────────────
    if args.batch:
        directory = args.image_path
        if not os.path.isdir(directory):
            print(f"Error: Not a directory: {directory}", file=sys.stderr)
            sys.exit(1)

        image_files = find_images(directory, recursive=args.recursive)
        if not image_files:
            print(f"No supported image files found in: {directory}")
            print(f"  Supported formats: {', '.join(sorted(IMAGE_EXTENSIONS))}")
            sys.exit(0)

        print(f"Found {len(image_files)} image(s) in {directory}")
        if args.recursive:
            print("  (searching recursively)")
        print()

        all_reports = []
        for i, img_path in enumerate(image_files, 1):
            try:
                report = analyze_image(img_path, threshold=args.threshold)
                all_reports.append(report)
            except Exception as e:
                print(f"Error analysing {os.path.basename(img_path)}: {e}", file=sys.stderr)

        # Progress / per-image output
        if args.summary:
            for i, r in enumerate(all_reports, 1):
                print(f"  [{i}/{len(all_reports)}] {os.path.basename(r.image_path)} -> {r.verdict} "
                      f"(AI: {r.overall_score:.0f}%)")
            print_batch_summary(all_reports, no_color=args.no_color)
        else:
            for report in all_reports:
                print_report(report, verbose=True, quiet=False, no_color=args.no_color)
            if len(all_reports) > 1:
                print_batch_summary(all_reports, no_color=args.no_color)

        # JSON batch output
        if args.json:
            print(json.dumps([r.to_dict() for r in all_reports], indent=2))
            return

        # HTML batch report
        if args.html:
            _generate_batch_html(args.html, all_reports)
            print(f"\nBatch HTML report written to: {args.html}")
        return

    # ── Single-File Mode ─────────────────────────────────────────────────
    if not os.path.exists(args.image_path):
        print(f"Error: File not found: {args.image_path}", file=sys.stderr)
        sys.exit(1)

    try:
        report = analyze_image(args.image_path, threshold=args.threshold)
    except Exception as e:
        print(f"Error analysing image: {e}", file=sys.stderr)
        sys.exit(1)

    if args.json:
        print(json.dumps(report.to_dict(), indent=2))
        return

    print_report(report, verbose=args.verbose or True, quiet=args.quiet, no_color=args.no_color)

    if args.html:
        html = generate_html_report(report, args.image_path)
        with open(args.html, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"HTML report written to: {args.html}")


if __name__ == "__main__":
    main()